[package]
name = "Project_3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
testcases = { path = "/home/tyler/CS310/Project_3/testcases"}